DEX-292 Add dummy comments to source code
skyflowapi/skyflow-iOS pull request #232
Opened 2023-07-13 07:28 UTC by shivkeshmadasu-skyflow

2023-08-28 22:07 UTC, manny-silva requested changes

2023-08-28 22:07 UTC, manny-silva commented on Sources/Skyflow/core/Client.swift
> +/// This is the description for Client Class.
Client for interacting with Skyflow.

2023-08-28 22:07 UTC, manny-silva commented on Sources/Skyflow/core/Configuration.swift
> +    This is the description for init method.
Configuration for the Skyflow client.

2023-08-28 22:07 UTC, manny-silva commented on Sources/Skyflow/core/container/ContainerProtocol.swift
> +/// Represents a protocol for container-related functionality.
Protocol for container-related functionality.

2023-08-28 22:07 UTC, manny-silva commented on Sources/Skyflow/elements/core/styles/Styles.swift
> +/// Contains different styles to apply on a Skyflow element.
Different styles to apply to a Skyflow element.

2023-08-28 22:07 UTC, manny-silva commented on Sources/Skyflow/elements/core/styles/Style.swift
> +/// Contains various styles for Skyflow elements.
Various styles for Skyflow elements.

2023-08-28 22:07 UTC, manny-silva commented on Sources/Skyflow/elements/core/CollectElementOptions.swift
> +/// Contains the additional options for Collect Element.
Additional options for a Collect Element.

2023-08-28 22:07 UTC, manny-silva commented on Sources/Skyflow/elements/validations/RegexMatchRule.swift
> +    validate the text using the specified regular expression.
"Validate"

2023-08-28 22:07 UTC, manny-silva commented on Sources/Skyflow/reveal/RevealContainer.swift
> +/// Wraps all Reveal Elements.
Container for all Reveal Elements.

2026-06-16 11:21 UTC, Devesh-Skyflow commented
This PR is being closed as it is no longer relevant. Please re-open or raise a new PR if these changes are still needed.

2026-06-16 11:38 UTC, Devesh-Skyflow commented
This PR is being closed as it is no longer relevant. Please re-open or raise a new PR if these changes are still needed.

2026-06-16 11:38 UTC, closed without merging